HOT_JIDS = """\
attxb6pv-0@zhizhiyaya.com/HuaLiao
j37oing0-0@zhizhiyaya.com/HuaLiao
avaw34h1-0@zhizhiyaya.com/HuaLiao
qj6ttk4h-0@zhizhiyaya.com/HuaLiao
ody33pya-0@zhizhiyaya.com/HuaLiao
pdwgpjy6-0@zhizhiyaya.com/HuaLiao
dkctjewg-0@zhizhiyaya.com/HuaLiao
7nb8seo-0@zhizhiyaya.com/HuaLiao
vt99iw39-0@zhizhiyaya.com/HuaLiao
qvt9ebbg-0@zhizhiyaya.com/HuaLiao
xet2oqf4-0@zhizhiyaya.com/HuaLiao
9lxf3wy9-0@zhizhiyaya.com/HuaLiao
e2n0jbqd-0@zhizhiyaya.com/HuaLiao
4sbcgjxq-0@zhizhiyaya.com/HuaLiao
284zg4p4-0@zhizhiyaya.com/HuaLiao
s8v1u4fu-0@zhizhiyaya.com/HuaLiao
j6rnu4u-0@zhizhiyaya.com/HuaLiao
f1i9eozl-0@zhizhiyaya.com/HuaLiao
hcj1r5hn-0@zhizhiyaya.com/HuaLiao
f7byjqcy-0@zhizhiyaya.com/HuaLiao
bvso2v10-0@zhizhiyaya.com/HuaLiao
t5zfc3qx-0@zhizhiyaya.com/HuaLiao
t14lbs2k-0@zhizhiyaya.com/HuaLiao
jfy033gs-0@zhizhiyaya.com/HuaLiao
5c26zy35-0@zhizhiyaya.com/HuaLiao
wwe9y2cg-0@zhizhiyaya.com/HuaLiao
mk2suy3u-0@zhizhiyaya.com/HuaLiao
k9bjcy8b-0@zhizhiyaya.com/HuaLiao
6dsorw3d-0@zhizhiyaya.com/HuaLiao
didukgmr-0@zhizhiyaya.com/HuaLiao
elkr1vni-0@zhizhiyaya.com/HuaLiao
npnb4i1l-0@zhizhiyaya.com/HuaLiao
g6xxbr6o-0@zhizhiyaya.com/HuaLiao
1jputwcs-0@zhizhiyaya.com/HuaLiao
lq4hqa3y-0@zhizhiyaya.com/HuaLiao
r7erihkx-0@zhizhiyaya.com/HuaLiao
lcpvh2s2-0@zhizhiyaya.com/HuaLiao
qda9mjvi-0@zhizhiyaya.com/HuaLiao
rqf7j2bk-0@zhizhiyaya.com/HuaLiao
qh9iuizm-0@zhizhiyaya.com/HuaLiao
h6llef55-0@zhizhiyaya.com/HuaLiao
ql607dut-0@zhizhiyaya.com/HuaLiao
ne6wjeyf-0@zhizhiyaya.com/HuaLiao
ow9b9n0r-0@zhizhiyaya.com/HuaLiao
l8nbu80o-0@zhizhiyaya.com/HuaLiao
6bw57apt-0@zhizhiyaya.com/HuaLiao
6iph4bsf-0@zhizhiyaya.com/HuaLiao
rhl630en-0@zhizhiyaya.com/HuaLiao
ih1qw5o1-0@zhizhiyaya.com/HuaLiao
r35i131j-0@zhizhiyaya.com/HuaLiao
15bd5oyj-0@zhizhiyaya.com/HuaLiao
f47gqde8-0@zhizhiyaya.com/HuaLiao
8a1etl2j-0@zhizhiyaya.com/HuaLiao
gkfy4hzk-0@zhizhiyaya.com/HuaLiao
9fo3q-0@zhizhiyaya.com/HuaLiao
bqfgacyx-0@zhizhiyaya.com/HuaLiao
777s36zk-0@zhizhiyaya.com/HuaLiao
71d444ge-0@zhizhiyaya.com/HuaLiao
ughlwq0j-0@zhizhiyaya.com/HuaLiao
a3hldeok-0@zhizhiyaya.com/HuaLiao
b404obqu-0@zhizhiyaya.com/HuaLiao
7viu0tkw-0@zhizhiyaya.com/HuaLiao
julo3sxk-0@zhizhiyaya.com/HuaLiao
s2k21qgu-0@zhizhiyaya.com/HuaLiao
kbohhii1-0@zhizhiyaya.com/HuaLiao
poqa5sl1-0@zhizhiyaya.com/HuaLiao
igcodsf6-0@zhizhiyaya.com/HuaLiao
u22cipgh-0@zhizhiyaya.com/HuaLiao
jly8sbk-0@zhizhiyaya.com/HuaLiao
lo2whqrj-0@zhizhiyaya.com/HuaLiao
ppokcmv5-0@zhizhiyaya.com/HuaLiao
nvuor0ph-0@zhizhiyaya.com/HuaLiao
h5w8q4tj-0@zhizhiyaya.com/HuaLiao
68xbbi4-0@zhizhiyaya.com/HuaLiao
0bqa2s8p-0@zhizhiyaya.com/HuaLiao
bbvo5dsh-0@zhizhiyaya.com/HuaLiao
iyrpy3b0-0@zhizhiyaya.com/HuaLiao
6uljt7sv-0@zhizhiyaya.com/HuaLiao
mghwrhcg-0@zhizhiyaya.com/HuaLiao
ee3ccoc5-0@zhizhiyaya.com/HuaLiao
pypg81ig-0@zhizhiyaya.com/HuaLiao
4ndz4aa2-0@zhizhiyaya.com/HuaLiao
cqc7hg1n-0@zhizhiyaya.com/HuaLiao
o5uphymq-0@zhizhiyaya.com/HuaLiao
1634trqf-0@zhizhiyaya.com/HuaLiao
w38qc0tw-0@zhizhiyaya.com/HuaLiao
qtv3mv4f-0@zhizhiyaya.com/HuaLiao
ihrw1ndy-0@zhizhiyaya.com/HuaLiao
foycsn38-0@zhizhiyaya.com/HuaLiao
7ubiairq-0@zhizhiyaya.com/HuaLiao
iji79li0-0@zhizhiyaya.com/HuaLiao
hbz0ofvw-0@zhizhiyaya.com/HuaLiao
3b52slv4-0@zhizhiyaya.com/HuaLiao
0tx8zl2q-0@zhizhiyaya.com/HuaLiao
mrx9gaua-0@zhizhiyaya.com/HuaLiao
hvxywryd-0@zhizhiyaya.com/HuaLiao
bih87cg6-0@zhizhiyaya.com/HuaLiao
844guaz-0@zhizhiyaya.com/HuaLiao
nw87d4b0-0@zhizhiyaya.com/HuaLiao
pftxy558-0@zhizhiyaya.com/HuaLiao
9s2220ra-0@zhizhiyaya.com/HuaLiao
l6cecrjv-0@zhizhiyaya.com/HuaLiao
gif333ex-0@zhizhiyaya.com/HuaLiao
zaveou2b-0@zhizhiyaya.com/HuaLiao
98u27uuu-0@zhizhiyaya.com/HuaLiao
cob28hd4-0@zhizhiyaya.com/HuaLiao
ygl9bjcf-0@zhizhiyaya.com/HuaLiao
iqagecvh-0@zhizhiyaya.com/HuaLiao
dn16fraq-0@zhizhiyaya.com/HuaLiao
zxqyi9sw-0@zhizhiyaya.com/HuaLiao
xz8proa2-0@zhizhiyaya.com/HuaLiao
s24kls52-0@zhizhiyaya.com/HuaLiao
ok21t54m-0@zhizhiyaya.com/HuaLiao
ftxqxax-0@zhizhiyaya.com/HuaLiao
h1q0fpys-0@zhizhiyaya.com/HuaLiao
yulegem6-0@zhizhiyaya.com/HuaLiao
oxkrf7ar-0@zhizhiyaya.com/HuaLiao
1jarxjjh-0@zhizhiyaya.com/HuaLiao
5pk81nim-0@zhizhiyaya.com/HuaLiao
1weyj36x-0@zhizhiyaya.com/HuaLiao
s52o2no1-0@zhizhiyaya.com/HuaLiao
35vfq9bk-0@zhizhiyaya.com/HuaLiao
jmr87pdu-0@zhizhiyaya.com/HuaLiao
cgp38746-0@zhizhiyaya.com/HuaLiao
i3zl0jjx-0@zhizhiyaya.com/HuaLiao
qpnjniqk-0@zhizhiyaya.com/HuaLiao
o4d64e07-0@zhizhiyaya.com/HuaLiao
89hr6du3-0@zhizhiyaya.com/HuaLiao
2ydh00jz-0@zhizhiyaya.com/HuaLiao
q3lq51ub-0@zhizhiyaya.com/HuaLiao
wtnwl8o0-0@zhizhiyaya.com/HuaLiao
gmm5mm56-0@zhizhiyaya.com/HuaLiao
wp1tb9p9-0@zhizhiyaya.com/HuaLiao
n0ghug79-0@zhizhiyaya.com/HuaLiao
qoptnf0m-0@zhizhiyaya.com/HuaLiao
u5frhbgc-0@zhizhiyaya.com/HuaLiao
62bxxy17-0@zhizhiyaya.com/HuaLiao
svespi6c-0@zhizhiyaya.com/HuaLiao
eswvjxo7-0@zhizhiyaya.com/HuaLiao
vi9az3nj-0@zhizhiyaya.com/HuaLiao
fx298xvj-0@zhizhiyaya.com/HuaLiao
m64phlnl-0@zhizhiyaya.com/HuaLiao
p73s3oba-0@zhizhiyaya.com/HuaLiao
6au1f3e5-0@zhizhiyaya.com/HuaLiao
84bcxxa-0@zhizhiyaya.com/HuaLiao
epox9tr9-0@zhizhiyaya.com/HuaLiao
y4xl5ipr-0@zhizhiyaya.com/HuaLiao
t7ac273b-0@zhizhiyaya.com/HuaLiao
l9en7hdf-0@zhizhiyaya.com/HuaLiao
qg9hcuds-0@zhizhiyaya.com/HuaLiao
otdarp9h-0@zhizhiyaya.com/HuaLiao
icqtbuj3-0@zhizhiyaya.com/HuaLiao
vp3xyxu9-0@zhizhiyaya.com/HuaLiao
zynka2gc-0@zhizhiyaya.com/HuaLiao
frg040l-0@zhizhiyaya.com/HuaLiao
12spvh9u-0@zhizhiyaya.com/HuaLiao
ertwmmi2-0@zhizhiyaya.com/HuaLiao
bwqlyg83-0@zhizhiyaya.com/HuaLiao
t2bvrez-0@zhizhiyaya.com/HuaLiao
uyueh7ja-0@zhizhiyaya.com/HuaLiao
9hpdv2r8-0@zhizhiyaya.com/HuaLiao
if4ic0v4-0@zhizhiyaya.com/HuaLiao
gu8j8a6j-0@zhizhiyaya.com/HuaLiao
hwuvgrwt-0@zhizhiyaya.com/HuaLiao
c8q4uo2e-0@zhizhiyaya.com/HuaLiao
uiemo4yv-0@zhizhiyaya.com/HuaLiao
9pwtynxg-0@zhizhiyaya.com/HuaLiao
yhwc40ye-0@zhizhiyaya.com/HuaLiao
vii91v7u-0@zhizhiyaya.com/HuaLiao
ai693-0@zhizhiyaya.com/HuaLiao
9r6vypx4-0@zhizhiyaya.com/HuaLiao
5gze10mq-0@zhizhiyaya.com/HuaLiao
7u7bu3jt-0@zhizhiyaya.com/HuaLiao
02fnng02-0@zhizhiyaya.com/HuaLiao
iexxtb5i-0@zhizhiyaya.com/HuaLiao
s5o01jzk-0@zhizhiyaya.com/HuaLiao
wj8ak82v-0@zhizhiyaya.com/HuaLiao
ok6xlrua-0@zhizhiyaya.com/HuaLiao
2nuguqsi-0@zhizhiyaya.com/HuaLiao
jngta7ki-0@zhizhiyaya.com/HuaLiao
f085c5wk-0@zhizhiyaya.com/HuaLiao
21bevp05-0@zhizhiyaya.com/HuaLiao
8xs955q6-0@zhizhiyaya.com/HuaLiao
8uu2qjm-0@zhizhiyaya.com/HuaLiao
pnkyubyc-0@zhizhiyaya.com/HuaLiao
5akncity-0@zhizhiyaya.com/HuaLiao
ec2mn9cw-0@zhizhiyaya.com/HuaLiao
5mielnle-0@zhizhiyaya.com/HuaLiao
etlxd1e9-0@zhizhiyaya.com/HuaLiao
t1p41rb5-0@zhizhiyaya.com/HuaLiao
6ut7838l-0@zhizhiyaya.com/HuaLiao
d2o2g9hd-0@zhizhiyaya.com/HuaLiao
5uhqrj4k-0@zhizhiyaya.com/HuaLiao
u8tjf0js-0@zhizhiyaya.com/HuaLiao
j8mo3t56-0@zhizhiyaya.com/HuaLiao
e5aujbf5-0@zhizhiyaya.com/HuaLiao
xtqgn0ti-0@zhizhiyaya.com/HuaLiao
1fnyzbgg-0@zhizhiyaya.com/HuaLiao
kwip255f-0@zhizhiyaya.com/HuaLiao
fh7f49pu-0@zhizhiyaya.com/HuaLiao
ke7p728b-0@zhizhiyaya.com/HuaLiao
kuqoploi-0@zhizhiyaya.com/HuaLiao
ku64y0tx-0@zhizhiyaya.com/HuaLiao
qgu8qhtg-0@zhizhiyaya.com/HuaLiao
9ijylbbw-0@zhizhiyaya.com/HuaLiao
bb29d95d-0@zhizhiyaya.com/HuaLiao
fhi06wsl-0@zhizhiyaya.com/HuaLiao
gcothtzd-0@zhizhiyaya.com/HuaLiao
utgll5bg-0@zhizhiyaya.com/HuaLiao
rlbjr1o7-0@zhizhiyaya.com/HuaLiao
5wzy7iav-0@zhizhiyaya.com/HuaLiao
dset4stg-0@zhizhiyaya.com/HuaLiao
w6j1m0en-0@zhizhiyaya.com/HuaLiao
dl2urj9f-0@zhizhiyaya.com/HuaLiao
xennptg3-0@zhizhiyaya.com/HuaLiao
vulfd8xz-0@zhizhiyaya.com/HuaLiao
wwcn52rd-0@zhizhiyaya.com/HuaLiao
qodm2irp-0@zhizhiyaya.com/HuaLiao
zufi88lg-0@zhizhiyaya.com/HuaLiao
evnhecys-0@zhizhiyaya.com/HuaLiao
lx1w5fhz-0@zhizhiyaya.com/HuaLiao
g3ulurv7-0@zhizhiyaya.com/HuaLiao
v4fym88y-0@zhizhiyaya.com/HuaLiao
onk40i78-0@zhizhiyaya.com/HuaLiao
su5p9xp1-0@zhizhiyaya.com/HuaLiao
xzqdpafv-0@zhizhiyaya.com/HuaLiao
981rgoc9-0@zhizhiyaya.com/HuaLiao
clz3n0kg-0@zhizhiyaya.com/HuaLiao
962pnbyi-0@zhizhiyaya.com/HuaLiao
9pfofjmi-0@zhizhiyaya.com/HuaLiao
dgxfnry1-0@zhizhiyaya.com/HuaLiao
aukvgz0p-0@zhizhiyaya.com/HuaLiao
mudnrwvm-0@zhizhiyaya.com/HuaLiao
zqrk0cjj-0@zhizhiyaya.com/HuaLiao
pf11n6xq-0@zhizhiyaya.com/HuaLiao
7l3yjr0s-0@zhizhiyaya.com/HuaLiao
hc6b1ck0-0@zhizhiyaya.com/HuaLiao
f7r1omvd-0@zhizhiyaya.com/HuaLiao
x6wpva9p-0@zhizhiyaya.com/HuaLiao
pbdiiydk-0@zhizhiyaya.com/HuaLiao
j8frmnl1-0@zhizhiyaya.com/HuaLiao
ctfd5r85-0@zhizhiyaya.com/HuaLiao
l3xtffg6-0@zhizhiyaya.com/HuaLiao
6keyq397-0@zhizhiyaya.com/HuaLiao
0y4exhcd-0@zhizhiyaya.com/HuaLiao
v2hba415-0@zhizhiyaya.com/HuaLiao
bw93mp78-0@zhizhiyaya.com/HuaLiao
12anh7u0-0@zhizhiyaya.com/HuaLiao
i5rjg9w3-0@zhizhiyaya.com/HuaLiao
4q8j4i5n-0@zhizhiyaya.com/HuaLiao
qgrby3d8-0@zhizhiyaya.com/HuaLiao
oxyccnk-0@zhizhiyaya.com/HuaLiao
5odv48h4-0@zhizhiyaya.com/HuaLiao
38jokn6k-0@zhizhiyaya.com/HuaLiao
svk83oqp-0@zhizhiyaya.com/HuaLiao
dupsdi6l-0@zhizhiyaya.com/HuaLiao
dbx2z-0@zhizhiyaya.com/HuaLiao
lqul13bu-0@zhizhiyaya.com/HuaLiao
siw7r-7@zhizhiyaya.com/HuaLiao
5mvcbhfv-0@zhizhiyaya.com/HuaLiao
svqzukx7-0@zhizhiyaya.com/HuaLiao
0u3jer57-0@zhizhiyaya.com/HuaLiao
f6iz5jac-0@zhizhiyaya.com/HuaLiao
ndb16zi0-0@zhizhiyaya.com/HuaLiao
agpvt5kg-0@zhizhiyaya.com/HuaLiao
5vrwfau9-0@zhizhiyaya.com/HuaLiao
4glarw3k-0@zhizhiyaya.com/HuaLiao
fos7jue3-0@zhizhiyaya.com/HuaLiao
91y2a71h-0@zhizhiyaya.com/HuaLiao
ewv6bnsx-0@zhizhiyaya.com/HuaLiao
sntw8s3w-0@zhizhiyaya.com/HuaLiao
s6k46ob-0@zhizhiyaya.com/HuaLiao
08du40tw-0@zhizhiyaya.com/HuaLiao
kcs8l8s4-0@zhizhiyaya.com/HuaLiao
klvxcnh-0@zhizhiyaya.com/HuaLiao
qbvxzprf-0@zhizhiyaya.com/HuaLiao
35clr15o-0@zhizhiyaya.com/HuaLiao
7ajb3ea4-0@zhizhiyaya.com/HuaLiao
rfuqsd21-0@zhizhiyaya.com/HuaLiao
dsxfl152-0@zhizhiyaya.com/HuaLiao
pcufedya-0@zhizhiyaya.com/HuaLiao
jxxc8a9c-0@zhizhiyaya.com/HuaLiao
gex8bc8h-0@zhizhiyaya.com/HuaLiao
zeg97iab-0@zhizhiyaya.com/HuaLiao
qbwk80ik-0@zhizhiyaya.com/HuaLiao
kpva754-0@zhizhiyaya.com/HuaLiao
0554s95t-0@zhizhiyaya.com/HuaLiao
cis8wssq-0@zhizhiyaya.com/HuaLiao
pvkr5s7g-0@zhizhiyaya.com/HuaLiao
gu2cq0yg-0@zhizhiyaya.com/HuaLiao
x1yq7nlf-0@zhizhiyaya.com/HuaLiao
s1xddrke-0@zhizhiyaya.com/HuaLiao
vfcbtvib-0@zhizhiyaya.com/HuaLiao
hw2di625-0@zhizhiyaya.com/HuaLiao
blqhpc7c-0@zhizhiyaya.com/HuaLiao
jobbm767-0@zhizhiyaya.com/HuaLiao
qkh5ayzk-0@zhizhiyaya.com/HuaLiao
ds59hwrn-0@zhizhiyaya.com/HuaLiao
3l24m538-0@zhizhiyaya.com/HuaLiao
igf9hmhe-0@zhizhiyaya.com/HuaLiao
1stg37vd-0@zhizhiyaya.com/HuaLiao
bbo13bke-0@zhizhiyaya.com/HuaLiao
hasx94fp-0@zhizhiyaya.com/HuaLiao
yhragugu-0@zhizhiyaya.com/HuaLiao
oafalt4n-0@zhizhiyaya.com/HuaLiao
kemar7lv-0@zhizhiyaya.com/HuaLiao\
""".splitlines()